apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.sirpi.in"
      path: "kv"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-secret"
          namespace: "external-secrets"
          key: "token"

