apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  releaseName: external-secrets
  targetNamespace: external-secrets
  interval: 10m
  chart:
    spec:
      chart: external-secrets
      version: 0.19.2
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: external-secrets
  values:
    installCRDs: true
    
    replicaCount: 2
    
    serviceAccount:
      create: true
      name: external-secrets
    
    rbac:
      create: true
    
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
    
    webhook:
      enabled: true
      port: 10250
    
    # Ensure CRDs use the correct stored version
    crds:
      createClusterExternalSecret: true
      createClusterSecretStore: true
      createPushSecret: true
      conversion:
        enabled: true
      
  install:
    createNamespace: true
    crds: Create
    remediation:
      retries: 3
    
  upgrade:
    crds: CreateReplace
    timeout: 15m
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
      remediateLastFailure: true
