apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  releaseName: external-secrets
  targetNamespace: external-secrets
  interval: 10m
  chart:
    spec:
      chart: external-secrets
      version: 0.19.2
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: external-secrets
  values:
    installCRDs: false  # Changed to false since we installed manually
    
    replicaCount: 1  # Start with 1 replica
    
    serviceAccount:
      create: true
    
    rbac:
      create: true
    
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    
    webhook:
      port: 10250
      
    certController:
      create: true
      
  install:
    createNamespace: false  # Already created
    crds: Skip  # Skip CRDs since we installed manually
    remediation:
      retries: 3
    
  upgrade:
    crds: Skip  # Always skip
    timeout: 15m
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
