apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 24h
  chart:
    spec:
      interval: 12h
      chart: longhorn
      version: "1.9.*"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
  valuesFrom:
    - kind: ConfigMap
      name: longhorn-values
