---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-backup-secret
  namespace: longhorn-system
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: longhorn-backup-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: "{{ .aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .aws_secret_access_key }}"
        AWS_ENDPOINTS: "https://s3.us-east-1.amazonaws.com"
  data:
    - secretKey: aws_access_key_id
      remoteRef:
        key: kv/data/longhorn
        property: aws_access_key_id
    - secretKey: aws_secret_access_key
      remoteRef:
        key: kv/data/longhorn
        property: aws_secret_access_key
