---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: micro
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: istio-config
  path: ./apps/base/microservices/api
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: first-api
      namespace: micro
