apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 24h
  chart:
    spec:
      interval: 12h
      chart: velero
      version: "11.*"
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: velero
  valuesFrom:
    - kind: ConfigMap
      name: velero-values
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    timeout: 15m
    remediation:
      retries: 2
      strategy: rollback
