apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 24h
  chart:
    spec:
      interval: 12h
      chart: kured
      version: "5.6.x"
      sourceRef:
        kind: HelmRepository
        name: kubereboot
        namespace: kube-system
  valuesFrom:
    - kind: ConfigMap
      name: kured-values

  upgrade:
    timeout: 15m
    remediation:
      retries: 2
      strategy: rollback
