apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aws-cloud-controller-manager
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: aws-cloud-controller-manager
      version: "0.0.8"
      sourceRef:
        kind: HelmRepository
        name: aws-cloud-controller-manager
        namespace: flux-system
  values:
    clusterName: kubernetes
    region: us-east-1
    serviceAccount:
      create: true
      name: cloud-controller-manager
    rbac:
      create: true
    credentials:
      create: true
      secretName: aws-credentials
      key: credentials
    args:
      - --cloud-provider=aws
      - --allocate-node-cidrs=true
      - --configure-cloud-routes=false
      - --controllers=cloud-node,cloud-node-lifecycle,service
      - --v=2
