apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aws-cloud-controller-manager
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: aws-cloud-controller-manager
      version: "0.0.8"
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: aws-cloud-controller-manager
        namespace: flux-system

  valuesFrom:
    - kind: ConfigMap
      name: ccm-values

  install:
    timeout: 5m
    remediation:
      retries: 3

  upgrade:
    timeout: 5m
    remediation:
      retries: 3
      strategy: rollback
