---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: aws-cloud-controller-manager
  namespace: kube-system
spec:
  interval: 1h
  url: https://kubernetes.github.io/cloud-provider-aws
