---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: postgres-tcp-route
  namespace: database
spec:
  parentRefs:
    - name: micro-gateway
      namespace: istio-system
      sectionName: postgres
  rules:
    - backendRefs:
        - name: postgres
          port: 5432
