apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 1h
  chart:
    spec:
      chart: external-dns
      version: "1.17.*"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
      interval: 12h

  valuesFrom:
    - kind: ConfigMap
      name: external-dns-values

  upgrade:
    timeout: 15m
    remediation:
      retries: 2
      strategy: rollback
