apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: do-token
  namespace: external-dns

spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: do-token
  data:
    - secretKey: DO_TOKEN
      remoteRef:
        key: kv/data/devops/digitalocean
        property: external-dns
