apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: alloy
      version: "1.*"
      sourceRef:
        name: grafana
        kind: HelmRepository

  valuesFrom:
    - kind: ConfigMap
      name: alloy-config

  upgrade:
    timeout: 15m
    remediation:
      retries: 2
      strategy: rollback

  dependsOn:
    - name: loki
