apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 12h
  chart:
    spec:
      interval: 12h
      chart: loki
      version: "6.*"
      sourceRef:
        name: grafana
        kind: HelmRepository
        namespace: monitoring

  valuesFrom:
    - kind: ConfigMap
      name: loki-values

  upgrade:
    timeout: 45m
    remediation:
      retries: 2
      strategy: rollback
