apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: kube-system
spec:
  interval: 12h
  chart:
    spec:
      chart: cluster-autoscaler
      version: "9.52.*"
      sourceRef:
        kind: HelmRepository
        name: cluster-autoscaler
        namespace: kube-system
      interval: 12h

  upgrade:
    remediation:
      retries: 3

  values:
    cloudProvider: aws

    # Image for Kubernetes 1.33
    image:
      repository: registry.k8s.io/autoscaling/cluster-autoscaler
      tag: v1.33.2

    # YOUR ASG — ONLY THIS ONE
    autoscalingGroups:
      - name: aws-k8s-cluster-worker-asg
        minSize: 0
        maxSize: 2

    # Disable auto-discovery
    autoDiscovery:
      clusterName: ""
      tags: []

    # AWS region
    extraArgs:
      region: us-east-1
      expander: least-waste
      scale-down-unneeded-time: 10m
      scale-down-utilization-threshold: 0.5
      skip-nodes-with-local-storage: false
      skip-nodes-with-system-pods: false

    # AWS credentials from secret
    extraEnvSecrets:
      AWS_ACCESS_KEY_ID:
        name: aws-credentials
        key: access-key-id
      AWS_SECRET_ACCESS_KEY:
        name: aws-credentials
        key: secret-access-key

    # Run on control plane
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists

    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane

    resources:
      limits:
        cpu: 200m
        memory: 400Mi
      requests:
        cpu: 100m
        memory: 200Mi

    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8085"
