apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: kube-system
spec:
  interval: 12h
  chart:
    spec:
      chart: cluster-autoscaler
      version: "9.52.*"
      sourceRef:
        kind: HelmRepository
        name: cluster-autoscaler
        namespace: kube-system
      interval: 12h

  upgrade:
    remediation:
      retries: 3

  values:
    # === AWS Provider ===
    cloudProvider: aws
    awsRegion: us-east-1 # ← OFFICIAL HELM VALUE

    # === Image ===
    image:
      repository: registry.k8s.io/autoscaling/cluster-autoscaler
      tag: v1.33.2

    # === Your Auto Scaling Group ===
    autoscalingGroups:
      - name: aws-k8s-cluster-worker-asg
        minSize: 0
        maxSize: 2

    # === Disable Auto-Discovery ===
    autoDiscovery:
      clusterName: ""
      tags: []

    # === Extra Args (CLI flags) ===
    extraArgs:
      expander: least-waste
      scale-down-unneeded-time: 10m
      scale-down-utilization-threshold: 0.5
      skip-nodes-with-local-storage: false
      skip-nodes-with-system-pods: false
      v: 4
      stderrthreshold: info

    # === AWS Credentials (from ExternalSecret) ===
    extraEnvSecrets:
      AWS_ACCESS_KEY_ID:
        name: aws-credentials
        key: access-key-id
      AWS_SECRET_ACCESS_KEY:
        name: aws-credentials
        key: secret-access-key

    # === Run on Control Plane ===
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists

    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule

    # === Resources ===
    resources:
      limits:
        cpu: 200m
        memory: 400Mi
      requests:
        cpu: 100m
        memory: 200Mi

    # === Observability ===
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8085"
