apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 30m
  dependsOn:
    - name: istio-base
      namespace: istio-system
  chart:
    spec:
      chart: istiod
      version: "1.26.x"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  valuesFrom:
    - kind: ConfigMap
      name: istio-values

  upgrade:
    timeout: 15m
    remediation:
      retries: 2
      strategy: rollback

