apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  interval: 30m
  chart:
    spec:
      chart: base
      version: "1.26.x"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  values:
    defaultRevision: default

  upgrade:
    timeout: 15m
    remediation:
      retries: 2
      strategy: rollback
