apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  interval: 30m
  dependsOn:
    - name: istiod
      namespace: istio-system
  chart:
    spec:
      chart: gateway
      version: "1.26.x"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  values:
    service:
      type: LoadBalancer
      ports:
        - name: status-port
          port: 15021
          protocol: TCP
          targetPort: 15021
        - name: http2
          port: 80
          protocol: TCP
          targetPort: 80
        - name: https
          port: 443
          protocol: TCP
          targetPort: 443
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
  upgrade:
    timeout: 15m
    remediation:
      retries: 2
      strategy: rollback
